### ISSUE TITLE
teams.get returns error 400 bad request

### ISSUE THREAD

**Issue by mission** [tsifrer/python-twitch-client#21]
```python
tclient = TwitchClient(client_id='<removed>')
teams = tclient.teams.get('area51gaming')
```
returns 400 error bad request

but
```python
tclient = TwitchClient(client_id='<removed>')
communities = tclient.communities.get_by_name('area51gaming')
```
returns fine

**Comment by tsifrer** [comment]
Hey!
Sorry for really late response. I've tested your exact commands and for both I'm getting 200 response with correct result. Are you sure that you `client_id` values were correct?

**Comment by mission** [comment]
well, ```tclient = TwitchClient(client_id='<removed>')
community = tclient.communities.get_by_name('area51gaming')
streams = tclient.streams.get_streams_in_community(community)``` works, so i would think the client_id is correct. hmmm..

**Comment by tsifrer** [comment]
Which version of python-twitch-client are you using?

**Comment by mission** [comment]
not sure what changed, but it is working now, i didnt change anything either

**Comment by tsifrer** [comment]
Weird. Glad it works now. Let me know if you have any more issues.
