### ISSUE TITLE
clips.get_top cannot be used

### ISSUE THREAD

**Issue by YuAnWu0000** [tsifrer/python-twitch-client#24]
clips = client.clips.get_top(game='League of Legends', limit=10)
AttributeError: 'TwitchClient' object has no attribute 'clips'

**Comment by tsifrer** [comment]
Sorry, clicked the button too soon. Clips will be included in next (0.4.0) release which I'll do in the next hour or so. Thanks for opening an issue.

**Comment by tsifrer** [comment]
If you now update python-twitch-client to version 0.4.0, clips endpoint should be there. :)

**Comment by YuAnWu0000** [comment]
Thanks a lot. It works!
