### ISSUE TITLE
Dependency for configparser is not met in a fresh 2.7 virtualenv

### ISSUE THREAD

**Issue by danielatdattrixdotcom** [tsifrer/python-twitch-client#27]
Subject says it all. A fresh 2.7 env gets an ImportError for configparser.

**Comment by danielatdattrixdotcom** [comment]
@tsifrer My mistake, I did mean 2.7.

**Comment by Kyle772** [comment]
Is there a short term solution for this for now? Also on 2.7 getting this error. Can someone upload the file so I can manually import it?

**Comment by danielatdattrixdotcom** [comment]
@Kyle772 Just use pip to install "configparser". The built-in one in 2.7 is imported as ConfigParser, which changed for Python 3. That is the easy fix for this, I opened an issue plain here since how @tsifrer wants to approach a fix is a personal choice.

**Comment by tsifrer** [comment]
I've just released a bugfix for this in version 0.5.1
Thank you for reporting this issue and proposing a solution.
Let me know if there are any further issues.
