### ISSUE TITLE
Possible to view my accounts current activity?

### ISSUE THREAD

**Issue by dannyvoid** [tsifrer/python-twitch-client#39]
Is it possible to use this to view who I'm currently watching?

**Comment by tsifrer** [comment]
Short answer: No. Twitch doesn't expose that data in any API endpoint.
Long answer:
I've looked a bit and there doesn't seem to be an endpoint that would expose what a user is watching at any point in time. After a quick search, I've found this but I don't think that's a solution. Also it's not implemented in this library: https://discuss.dev.twitch.tv/t/find-out-what-a-user-is-watching-anywhere-on-twitch/13866
