### ISSUE TITLE
games.get_top brings less items above 10

### ISSUE THREAD

**Issue by kht1992** [tsifrer/python-twitch-client#54]
client.games.get_top(10) and client.games.get_top(11) gets same number of items, which is 10.
That means client.games.get_top(12) brings 11 items, client.games.get_top(13) brings 12 items and so on.

**Comment by tsifrer** [comment]
I haven't tested this reported issue, but it is not something we can fix. Looking trough the function, we just pass the limit to Twitch API and then we give you back whatever we get from Twtich API. So looks like the bug is on Twitch side.
