### ISSUE TITLE
streams?community_id endpoint

### ISSUE THREAD

**Issue by Gretorp** [tsifrer/python-twitch-client#6]
Hello.  

super nub just getting into programming/API stuff.  I apologize for my ignorance.  

There's a "/streams?community_id=" endpoint in v5 that I'm wondering if you could add.  Is it possible to add that? Thanks so much!

Source: https://discuss.dev.twitch.tv/t/communities-api-release/9211 (from twitch staff, top post)

**Comment by tsifrer** [comment]
Hey! Thanks for the interest :) Sorry for a late reply, for some reason I had my notifications turned off on github.
I've added this enpoint under `streams`. Example here: http://python-twitch-client.readthedocs.io/en/latest/api/streams.html#twitch.api.streams.Streams.get_streams_in_community

This new functionality will be as part of the 0.3.0 release which will be released probably by the end of this week.

**Comment by Gretorp** [comment]
Thanks tsifrer!
