### ISSUE TITLE
channels.get() API url is incorrect

### ISSUE THREAD

**Issue by tsumare** [tsifrer/python-twitch-client#8]
API requests with channels.get() fail because the endpoint is 'channel' and the function requests 'channels'

Offending line: https://github.com/tsifrer/python-twitch-client/blob/4c12180368211d2c2d176c068bc696d61239a6c6/twitch/api/channels.py#L14

API Documentation: https://dev.twitch.tv/docs/v5/reference/channels/#get-channel

**Comment by m3adow** [comment]
Will this fix be supplied to Pypi automatically?

**Comment by tsifrer** [comment]
Unfortunately not. I'll need to do a manual release after I get home from work.

Thanks for the report and bugfix!

**Comment by m3adow** [comment]
Thanks for your work!

**Comment by tsumare** [comment]
Thanks for the quick resolution!  Can you leave a note here when Pypi is updated, @tsifrer?

**Comment by tsifrer** [comment]
I've now released version 0.3.0 and is available on pypi. Changes are documented in the changelog: https://github.com/tsifrer/python-twitch-client/blob/master/CHANGELOG.md

Thanks for the report and the fix! :)
